Resources:
# Create Producer User Pool
  CognitoProducerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: 'OFF'
      UserPoolName:
        Fn::Sub: Tzero${self:custom.stage}_ProducerUserPool
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      EmailVerificationSubject:  LambdaRegistration Link
      EmailVerificationMessage: 'Dear Producer,Welcome to Telkom T-Zero CommunityThank
        you for Registering as a producer, Complete your registration by clicking
        the link below to verify your email address.Verify Email{####}  Click here
        to Login : http://cloudtechnologies.cloud/login Thanks,Team  '
      Schema:
      - Name: name
        AttributeDataType: String
        Mutable: true
        Required: true
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: true
      - Name: profile
        AttributeDataType: String
        Mutable: false
        Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
# Create Producer App Client
  CognitoProducerAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Sub: Tzero${self:custom.stage}_ProducerAppClient
      GenerateSecret: false
      UserPoolId:
        Ref: CognitoProducerUserPool

# Create Consumer User Pool
  CognitoConsumerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: 'OFF'
      UserPoolName:
        Fn::Sub: Tzero${self:custom.stage}_ConsumerUserPool
      UsernameAttributes:
      - phone_number
      Schema:
      - Name: name
        AttributeDataType: String
        Mutable: true
        Required: true
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: true
      - Name: profile
        AttributeDataType: String
        Mutable: false
        Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
# Create Consumer App Client
  CognitoConsumerAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Sub: Tzero${self:custom.stage}_ConsumerAppClient
      GenerateSecret: false
      UserPoolId:
        Ref: CognitoConsumerUserPool

# Print out the Id of the User Pool that is created
# Outputs:
#   UserPoolId:
#     Value:
#       Ref: CognitoProducerUserPool
#   UserPoolClientId:
#     Value:
#       Ref: CognitoProducerAppClient

#   UserPoolId:
#     Value:
#       Ref: CognitoConsumerUserPool
#   UserPoolClientId:
#     Value:
#       Ref: CognitoConsumerAppClient